## Part5 questions
use online_learning_platform;

## Calculate the total course purchase value for each student
with total_course_value as (
	select s.full_name,
    sum(c.price) as total_amount_spend
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
order by sum(c.price) desc
)
select * from total_course_value
;

## Find students whose total course value is higher than the average student value
with total_value as (
	select s.full_name,
    sum(c.price) as total_amount_spend
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
), avg_value as (
	select round(avg(total_amount_spend),2) as avg_spend_value
    from total_value
)

select tv.full_name,
		tv.total_amount_spend
from total_value tv
cross join avg_value av
where tv.total_amount_spend > av.avg_spend_value
;

## Rank students based on their total course value spending from highest to lowest
select s.full_name,
    sum(c.price) as total_amount,
    dense_rank() over(order by sum(c.price) desc) as rank_given
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
order by total_amount desc;

## Identify the top 10% highest value students based on course spending
with student_spend as (
select s.full_name,
    sum(c.price) as total_amount,
    ntile(10) over (order by sum(c.price) desc) as spend_bucket
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
)
select * from student_spend
where spend_bucket=1
;

## Calculate total revenue generated by each course
select c.course_name,
    sum(c.price) as total_revenue
from courses c
join enrollments e on e.course_id = c.course_id
group by c.course_name
order by sum(c.price) desc
;

## Identify students who never progressed beyond 20% in any enrolled course
select s.full_name
from students s
join enrollments e on e.student_id = s.student_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
group by s.full_name
having max(cp.completed_percent) <= 20
;

## Find courses with highest average completion percentage
select c.course_name,
	round(avg(cp.completed_percent),2) as avg_comp_percentage
from courses c 
join enrollments e on e.course_id = c.course_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
group by c.course_name
order by avg_comp_percentage desc
;

## Classify students into high, moderate, low engagement based on average completion
select c.course_name,
	round(avg(cp.completed_percent),2) as avg_comp_percentage,
    case when round(avg(cp.completed_percent),2) > 55 then 'High engagement'
		when round(avg(cp.completed_percent),2) between 45 and 55 then 'Moderate engagement'
			else 'Low engagement'
            end as engagement
from courses c 
join enrollments e on e.course_id = c.course_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
group by c.course_name
order by avg_comp_percentage desc
;

## Find students who enrolled in courses but never started progress
select s.full_name
from students s
join enrollments e on e.student_id = s.student_id
left join course_progress cp on cp.enrollment_id = e.enrollment_id
group by s.full_name
having max(coalesce(cp.completed_percent, 0)) = 0;

## Show month wise enrollment count and compare with previous month
select month_name,
total_enrollments,
lag(total_enrollments) over( order by month_num) as prev_month_enroll
from (
select month(enroll_date) as month_num,
monthname(enroll_date) as month_name,
count(*) as total_enrollments
from enrollments
group by MONTH(enroll_date), month_name
order by MONTH(enroll_date)
) t
;

## Calculate month-over-month enrollment growth percentage
select month_name,
total_enrollments,
prev_month_enroll,
round((((prev_month_enroll - total_enrollments)/ total_enrollments) * 100),2) as month_over_month
from (
select month(enroll_date) as month_num,
monthname(enroll_date) as month_name,
count(*) as total_enrollments,
lag(count(*)) over( order by month(enroll_date)) as prev_month_enroll
from enrollments
group by MONTH(enroll_date), month_name
order by MONTH(enroll_date)
) t
;

## Identify students whose course completion improved over time
select *
from (
select s.full_name,
c.course_name,
cp.completed_percent,
lag(cp.completed_percent) over (partition by s.student_id, c.course_id order by e.enroll_date) as prev_completion
from students s 
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
) t
where completed_percent > prev_completion
;

## Find courses with high enrollments but low average completion rates
with avg_rate as (
select c.course_id,
		c.course_name,
		count(e.enrollment_id) as total_enrollments,
        round(avg(completed_percent),2) as avg_comp_rate
from courses c
join enrollments e on e.course_id = c.course_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
group by c.course_id, c.course_name
)
select course_name,
total_enrollments,
avg_comp_rate
from avg_rate
where total_enrollments > (
	select avg(total_enrollments) from avg_rate
)
;

## Create a funnel showing enrolled, active, and completed learners
select
    count(distinct e.student_id) as enrolled_learners,
  --   sum(case 
--             when cp.completed_percent > 0 
--             then 1 else 0 
--         end) as active_learners,
--     sum(case 
--             when cp.completed_percent = 100 
--             then 1 else 0 
--         end) as completed_learners
count(distinct case
		when cp.completed_percent > 0 
		then s.student_id 
	end) as active_learners,
	count(distinct case 
		when cp.completed_percent = 100 
		then s.student_id 
	end) as completed_learners
from enrollments e
left join students s on s.student_id = e.student_id
left join course_progress cp on cp.enrollment_id = e.enrollment_id;

## Identify students enrolled in more than one course
select s.full_name,
		count(*) as courses_enrolled
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
having count(*) > 1
order by courses_enrolled desc
;

## Find students who are contributing to the top 80% of total platform revenue
with student_spend as (
select s.full_name,
    sum(c.price) as total_amount,
    ntile(10) over (order by sum(c.price) desc) as spend_bucket
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
group by s.full_name
),
revenue_rank as (
select *,
sum(total_amount) over() as total_revenue,
sum(total_amount) over (order by total_amount desc) as cumulative_revenue
from student_spend
)
select full_name,
total_amount
 from revenue_rank
where cumulative_revenue <= 0.8 * total_revenue;
;

## Identify months with highest enrollment activity
select monthname(enroll_date) as month_name,
count(*) as total_enrollments
from enrollments
group by month_name
order by total_enrollments desc
;


## Find students whose course engagement is declining over time
select * 
from (
select s.full_name,
c.course_name,
cp.completed_percent as current_percent,
lag(completed_percent) 
	over( partition by full_name, course_name order by enroll_date) as prev_engagement
from students s 
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
join course_progress cp on cp.enrollment_id = e.enrollment_id
) t
where prev_engagement > current_percent
;

## Identify courses that bring most new students on signup date
select
		c.course_name,
		count(distinct s.student_id) as students_enrolled
from students s
join enrollments e on e.student_id = s.student_id
join courses c on c.course_id = e.course_id
where e.enroll_date = s.signup_date
group by c.course_name
order by students_enrolled desc
;

## Generate a platform level summary showing student count, activity and learning health.
select count(distinct s.student_id) as total_students,
	count(distinct e.student_id) as enrolled_students,
  --   sum(case 
-- 			when cp.completed_percent > 0 then 1 else 0 end ) 
--             as "Active learners",
-- 	sum(case 
-- 			when cp.completed_percent = 100 then 1 else 0 end) 
--             as  "Completed learners",
	count(distinct case
		when cp.completed_percent > 0 
		then s.student_id 
	end) as active_learners,
	count(distinct case 
		when cp.completed_percent = 100 
		then s.student_id 
	end) as completed_learners,
    case when avg(cp.completed_percent) > 70 then "Healthy engagement"
		when avg(cp.completed_percent) between 30 and 70 then "Moderate engagement"
        else "At risk"
        end as learning_health
from students s 
left join enrollments e on e.student_id = s.student_id
left join course_progress cp on cp.enrollment_id = e.enrollment_id
;